---

- name: RabbitMQ trusted keys
  apt_key:
    url: "{{ item }}"
    state: present
  with_items:
    - https://www.rabbitmq.com/rabbitmq-release-signing-key.asc
    - https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc

- name: RabbitMQ apt repos
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "deb https://dl.bintray.com/rabbitmq/debian {{ ansible_distribution_release }} main"
    - "deb http://binaries.erlang-solutions.com/debian {{ ansible_distribution_release }} contrib"

- name: RabbitMQ packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
    allow_unauthenticated: yes
  with_items: "{{ rabbitmq_packages }}"

- name: Ensure Rabbitmq service started and enabled
  service:
    name: rabbitmq-server
    enabled: yes
    state: started

- name: Configure RabbitMQ
  template:
    dest: "/etc/rabbitmq/rabbitmq.config"
    group: "rabbitmq"
    mode: 0644
    owner: "rabbitmq"
    src: 'rabbitmq.config.j2'
  notify: Restart RabbitMQ

- name: RabbitMQ environment-specific configuration
  template:
    dest: '/etc/rabbitmq/rabbitmq-env.conf'
    group: 'rabbitmq'
    mode: 0644
    owner: 'rabbitmq'
    src: 'rabbitmq-env.conf.j2'
  notify: Restart RabbitMQ

- name: RabbitMQ plugins
  rabbitmq_plugin:
    names: "{{ rabbitmq_plugins|join(',') }}"
    state: enabled
